### ISSUE TITLE
TypeError: $(...).ionRangeSlider is not a function

### ISSUE THREAD

**Issue by damienmaguire** [dimecho/ESP8266-EMW-Charger#1]
Trying to run with firefox browser on windoze 7 results in the page loading but failing to send data over serial when start charger button is pressed. Results from inspector :

TypeError: $(...).ionRangeSlider is not a function
TypeError: $.notify is not a function

**Comment by dimecho** [comment]
You did not flash SPIFFS correctly (probably plain text). SPIFFS are special build with gzip -> spiffs-build-win.ps1

Format esp8266 by going into http://192.168.4.2/format then go to http://192.168.4.2/update and upload SPIFFS binary.

**Comment by damienmaguire** [comment]
Did that and get ,
Update error: ERROR[4]: Not Enough Space 
192.168.4.2/format gives ,
<b>Format OK</b><br/>Total Flash Size: 2097152<br>SPIFFS Size: 1073678988<br>SPIFFS Used: 1073669784

**Comment by dimecho** [comment]
If you used Arduino IDE to flash sketch make sure you select SPIFFS size.

![spiffs](https://user-images.githubusercontent.com/4879613/73775395-9f080680-473a-11ea-90f8-90ef3cb6c0e2.png)

**Comment by damienmaguire** [comment]
Did that and get ,
Update error: ERROR[4]: Not Enough Space 
192.168.4.2/format gives ,
<b>Format OK</b><br/>Total Flash Size: 2097152<br>SPIFFS Size: 1073678988<br>SPIFFS Used: 1073669784
